# Generated by Django 4.2.9 on 2024-02-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbta_id', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('municipality', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.IntegerField()),
                ('wheelchair_boarding', models.IntegerField()),
                ('at_street', models.CharField(default=None, max_length=255, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('on_street', models.CharField(default=None, max_length=255, null=True)),
                ('platform_code', models.CharField(default=None, max_length=255, null=True)),
                ('platform_name', models.CharField(default=None, max_length=255, null=True)),
                ('vehicle_type', models.IntegerField(default=None, null=True)),
                ('zone_id', models.CharField(default=None, max_length=255, null=True)),
                ('parent_station', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_stops', to='commuter_rail_departure_departures.stop')),
            ],
        ),
    ]
