# Generated by Django 4.2.9 on 2024-02-05 21:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commuter_rail_departure_departures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbta_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('direction_destinations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('direction_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('fare_class', models.CharField(max_length=25)),
                ('long_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=25)),
                ('sort_order', models.IntegerField()),
                ('text_color', models.CharField(max_length=25)),
                ('line_id', models.CharField(max_length=25)),
            ],
        ),
    ]
