from commuter_rail_departure_core.types.prediction import PredictionData
from commuter_rail_departure_core.types.route import RouteData
from commuter_rail_departure_core.types.schedule import ScheduleData